[package]
name = "cjson-rs"
description = "Rust bindings for the cJSON library"
license = "MIT"
version = "0.2.2"
edition = "2021"

[build-dependencies]
bindgen = "0.70.1"

[dependencies]
libc = "0.2.161"
