name: Continuous Integration

on:
    push:
        branches:
            main
    pull_request:
        branches:
            main

jobs:
    ci:
        runs-on: ubuntu-latest
        env:
          CJSON_INCLUDE_PATH: /usr/include/cjson
          CJSON_LIB_PATH: /usr/local/lib

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Install cJSON
            run:  sudo apt-get install -y libcjson-dev

          - name: Set up Rust toolchain
            uses: actions-rs/toolchain@v1
            with:
                toolchain: stable
                override: true

          - name: Test
            run: cargo test --verbose
